language: dart
# Speed up builds by using containerization.
sudo: false
dart:
- stable
- dev
with_content_shell: false
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - set -e
  - pub run test test/rxdart_test.dart
after_success:
  - pub global activate dart_coveralls
  - pub global run dart_coveralls:dart_coveralls report --debug --exclude-test-files --token=$REPO_TOKEN test/rxdart_test.dart